# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
            - name: Markdown Report
  # You may pin to the exact commit or the version.
  # uses: dtinth/markdown-report-action@af8143d37cced4c514fd67539a2e58c2f432da09
  uses: dtinth/markdown-report-action@v1.0.0
  with:
    # Check name
    name: 
    # Title
    title: 
    # Path to the Markdown file
    body-file: 
          
